### ISSUE TITLE
ED team claims, that AGM-62 warhead is not according to database

### ISSUE THREAD

**Issue by GumidekCZ** [Quaggles/dcs-lua-datamine#6]
https://forum.dcs.world/topic/286327-agm-62-walleye-ii-worng-warhead-mass/#comment-5011088
Can the source of data be checked for the database warhead for AGM-62?

**Comment by Quaggles** [comment]
The lua tables are correct but they can be a bit misleading.

While the Walleye II is listed as having a 2,000lb / 900kg explosive mass it's a shaped charge warhead, looking back at the archived version of `warheads.lua` from before the source files were removed from the sim we can see how they wrote the functions that created the final values:

```lua
local explosivePercent = 0.4

local function calcPiercingMass(warhead)
    warhead.piercing_mass  = warhead.mass;
    if (warhead.expl_mass/warhead.mass > 0.1) then
        warhead.piercing_mass  = warhead.mass/5.0;
    end
end

function cumulative_warhead(power, caliber)
    local res = {};
    res.caliber = caliber;
    res.expl_mass = power*explosivePercent;
    res.mass = res.expl_mass;
    res.other_factors = {1, 1, 1};
    res.obj_factors = {1, 1};
    res.concrete_factors = {1, 1, 1};
    res.cumulative_factor = 3.0;
    res.concrete_obj_factor = 0.0;
    res.cumulative_thickness = 0.2;
    calcPiercingMass(res)
    return res;
end

warheads["AGM_62"] = cumulative_warhead(914, 457); 	-- 2015 lb Walleye 2 warhead 
```

So you can see that for shaped charge warheads they have a global multiplier `explosivePercent` to reduce the `expl_mass` to 40% of what the warhead TNT charge is (I assume to simulate it focusing its explosive force forward and not spherically like a fragmentation bomb). Unfortunately this coincidentally made it look like it was modelled after the Walleye I.

Walleye I Warhead: `825lb = 374.2kg`
Walleye II Shaped Warhead: `2000lb = 914kg * 0.4 = 365.6kg` expl_mass

Then they give it a `cumulative_factor = 3.0` which means it will do 3x the damage to a target it directly hits to simulate shaped charge damage.

For full documentation of what the warhead parameters mean check the comments section in the readme: https://github.com/Quaggles/dcs-lua-datamine/#_gwarheads

**Comment by GumidekCZ** [comment]
Many thanks for explanation, Im glad I can learn something.

**Comment by TheTurbs** [comment]
> The lua tables are correct but they can be a bit misleading.
> 
> While the Walleye II is listed as having a 2,000lb / 900kg explosive mass it's a shaped charge warhead, looking back at the archived version of `warheads.lua` from before the source files were removed from the sim we can see how they wrote the functions that created the final values:
> 
> ```lua
> local explosivePercent = 0.4
> 
> local function calcPiercingMass(warhead)
>     warhead.piercing_mass  = warhead.mass;
>     if (warhead.expl_mass/warhead.mass > 0.1) then
>         warhead.piercing_mass  = warhead.mass/5.0;
>     end
> end
> 
> function cumulative_warhead(power, caliber)
>     local res = {};
>     res.caliber = caliber;
>     res.expl_mass = power*explosivePercent;
>     res.mass = res.expl_mass;
>     res.other_factors = {1, 1, 1};
>     res.obj_factors = {1, 1};
>     res.concrete_factors = {1, 1, 1};
>     res.cumulative_factor = 3.0;
>     res.concrete_obj_factor = 0.0;
>     res.cumulative_thickness = 0.2;
>     calcPiercingMass(res)
>     return res;
> end
> 
> warheads["AGM_62"] = cumulative_warhead(914, 457); 	-- 2015 lb Walleye 2 warhead 
> ```
> 
> So you can see that for shaped charge warheads they have a global multiplier `explosivePercent` to reduce the `expl_mass` to 40% of what the warhead TNT charge is (I assume to simulate it focusing its explosive force forward and not spherically like a fragmentation bomb). Unfortunately this coincidentally made it look like it was modelled after the Walleye I.
> 
> Walleye I Warhead: `825lb = 374.2kg` Walleye II Shaped Warhead: `2000lb = 914kg * 0.4 = 365.6kg` expl_mass
> 
> Then they give it a `cumulative_factor = 3.0` which means it will do 3x the damage to a target it directly hits to simulate shaped charge damage.
> 
> For full documentation of what the warhead parameters mean check the comments section in the readme: https://github.com/Quaggles/dcs-lua-datamine/#_gwarheads

Hi Quaggles, great discussion.  I ran your lua exporter as my group was having a discussion about the Harpoon.  Based on the latest export it seems the harpoon may be borked.  Could you confirm?

**Comment by Quaggles** [comment]
What do you mean by borked, can you be more specific?

**Comment by TheTurbs** [comment]
Sure can, apologies Borked is the term we use when we see something potentially not correct.  My squadron ran into an issue the other night where we launched about 40 AGM-84D Harpoons at a Pyotr Battlecruiser.  For the harpoons that did hit they did very little damage.  Another squadron of ours came in right after us and took the ship out with 3-4 AGM-62 Walleyes.

Looking through google I found your github resource for extracting database information for the warheads.  AGM-84D listed on Wiki has a warhead mass of 221kg.  When I ran your script for extracting data I found the warhead expl_mass is listed as 88.4 with a cumulative_factor of 2.  Is there something I am missing that would make the 88.4 result in an explosion mass of 221 kg?

**Comment by TheTurbs** [comment]
in more broad terms, we're trying to determine if the Harpoon warhead damage is realistic.

**Comment by Quaggles** [comment]
> Is there something I am missing that would make the 88.4 result in an explosion mass of 221 kg?

Yeah so for the AGM-84 it has the following line `obj_factors = { 2.5, 1 },` which is described as:

>  obj_factors = { HE1, HE2 },
High-explosive action coefficient when it hits a ground object (equipment):
HE1 - explosive damaging effect (expl_mass *HE1)
HE2 - explosion effect size

So in the case of a direct hit it would be `88.4kg (expl_mass) * 2.5 = 221kg`, I assume this was done so only direct hits would deal the full damage of the warhead so if it hit the water/ground or something it wouldn't do as much splash damage.

Like the AGM-62 the AGM-84D also has a `cumulative_factor` defined which also does extra damage **only if** it hits armor it can penetrate, but this effect is not as powerfull as the Walleye due to the smaller warhead. Some ships do have a [modular damage model](https://imgur.com/a/Zy0KzX4) but I'm not sure how their armour thickness is defined, in ground units there is a [damage model table](https://github.com/Quaggles/dcs-lua-datamine/blob/master/_G/db/Units/Cars/Car/M-1%20Abrams.lua#L6) that links the plates from the model to thickness values but the ships don't have that, they might have some default value in a place the dataminer can't view.

Looking at just the warhead comments and assuming both `cumulative_factor` and `obj_factors` apply when hitting the ship the damage would be as follows:
`(expl_mass * obj_factors[1]) + (expl_mass * cumulative_factor[1])`
AGM-62 = 1460
AGM-84D = 397.8

Whether this is realistic is another question, I'm not an expert on the IRL effects of anti ship warheads unfortunately haha

**Comment by TheTurbs** [comment]
Ah this makes much more sense to me now.  Thank you for taking the time to answer.
